# PySharpe developer tooling — run `make help` for all targets.
#
# Requirements: uv (https://docs.astral.sh/uv/). `uv run` creates/syncs the
# project virtualenv from uv.lock, so no manual venv setup is needed.

.DEFAULT_GOAL := help

# Minimum total coverage required by `make test` (currently ~79%).
# Raise to 80 once visualization/ and workflows.py gain test coverage.
COVERAGE_FLOOR := 75

PYTEST_COV := --cov=src/pysharpe \
	--cov-report=term-missing \
	--cov-report=xml:coverage.xml \
	--cov-fail-under=$(COVERAGE_FLOOR)

# Runtime data directories cleared by `clean` (contents are regenerated by
# the pipeline; .gitkeep placeholders are preserved).  data/portfolio/ is
# deliberately excluded — it holds user portfolio definitions.
DATA_CLEAN_DIRS := data/cache data/exports data/info data/logs data/price_hist

.PHONY: help install dev-install lint lint-fix format format-check typecheck test test-cov build build_docs docs-serve clean check strict repomix all

help:  ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-16s\033[0m %s\n", $$1, $$2}'

install:  ## Install the package with development dependencies
	uv pip install -e ".[dev]"

dev-install: install  ## Alias for `install`

lint:  ## Run ruff linter + formatting check
	uv run ruff check .
	uv run ruff format --check .

lint-fix:  ## Auto-fix ruff lint violations where possible
	uv run ruff check --fix .

format:  ## Apply ruff formatting in place
	uv run ruff format .

format-check:  ## Check formatting without modifying files
	uv run ruff format --check .

typecheck:  ## Run pyright; errors AND warnings are fatal
	uv run pyright --warnings src/

test:  ## Run pytest with coverage (fails below $(COVERAGE_FLOOR)%)
	uv run pytest $(PYTEST_COV)

test-cov: test  ## Alias for `test`

build:  ## Build sdist and wheel distributions
	uv build

build_docs:  ## Build the MkDocs site (strict mode: warnings are fatal)
	uv run mkdocs build --strict

docs-serve:  ## Serve the docs locally with live reload
	uv run mkdocs serve

repomix:  ## Pack the codebase for AI analysis into repomix-output.xml
	repomix

clean:  ## Remove build artifacts, caches, coverage output, the built docs site, and local data artefacts (keeps .gitkeep)
	@rm -rf dist/ build/ site/ *.egg-info/ .pytest_cache/ .mypy_cache/ .ruff_cache/ htmlcov/
	@rm -f coverage.xml .coverage pytest_results.log
	@find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	@for dir in $(DATA_CLEAN_DIRS); do \
		find $$dir -type f ! -name ".gitkeep" -delete 2>/dev/null || true; \
	done

check: lint typecheck test  ## Full pre-commit gate: lint + typecheck + tests with coverage

strict:  ## Run tests with the pyright smoke-check made fatal
	PYSHARPE_REQUIRE_PYRIGHT=1 uv run pytest

all: format lint typecheck test build build_docs repomix  ## Full pipeline: format in place, then lint, typecheck, tests, package + docs builds, and repomix pack
