"""Dollar-cost averaging projection utilities."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Optional

import numpy as np

from . import utils as viz_utils

if TYPE_CHECKING:  # pragma: no cover - type checking aide
    import matplotlib.pyplot as plt


def _require_matplotlib():  # pragma: no cover - backward compatibility helper
    return viz_utils.require_matplotlib()


@dataclass(frozen=True)
class DCAProjection:
    """Container for the simulated dollar-cost averaging series.

    Example:
        >>> import numpy as np
        >>> from pysharpe.visualization.dca import DCAProjection
        >>> projection = DCAProjection(np.arange(3), np.array([100, 200, 300]), np.array([105, 210, 320]))
        >>> projection.final_balance()
        320.0
    """

    months: np.ndarray
    contributions: np.ndarray
    balances: np.ndarray

    def final_balance(self) -> float:
        return float(self.balances[-1])

    def final_contribution(self) -> float:
        return float(self.contributions[-1])


def simulate_dca(
    *,
    months: int,
    initial_investment: float,
    monthly_contribution: float,
    annual_return_rate: float,
) -> DCAProjection:
    """Simulate a dollar-cost averaging schedule.

    Parameters
    ----------
    months:
        Number of months to project. Must be greater than zero.
    initial_investment:
        Lump sum deployed at month zero.
    monthly_contribution:
        Amount invested at the end of every month.
    annual_return_rate:
        Expected annual compound rate (expressed as 0.10 for 10%).
    Example:
        >>> from pysharpe.visualization.dca import simulate_dca
        >>> simulate_dca(months=3, initial_investment=100.0, monthly_contribution=10.0, annual_return_rate=0.12).final_balance()  # doctest: +ELLIPSIS
        121...
    """

    if months <= 0:
        raise ValueError("months must be positive")

    if annual_return_rate <= -1:
        raise ValueError("annual_return_rate must be greater than -100%")

    month_index = np.arange(months, dtype=int)
    contributions = initial_investment + monthly_contribution * month_index.astype(float)

    monthly_rate = (1 + annual_return_rate) ** (1 / 12) - 1
    growth_factor = 1.0 + monthly_rate

    powers = growth_factor ** month_index.astype(float)
    balances = powers * initial_investment

    if not np.isclose(monthly_rate, 0.0):
        balances += monthly_contribution * growth_factor * (powers - 1) / monthly_rate
    else:
        balances += monthly_contribution * month_index.astype(float)

    balances = balances.astype(float)

    return DCAProjection(months=month_index, contributions=contributions, balances=balances)


def plot_dca_projection(
    projection: DCAProjection,
    *,
    ax: Optional["plt.Axes"] = None,
    show: bool = False,
    title: Optional[str] = None,
):
    """Plot the cumulative balance and contributions for a DCA projection.

    Args:
        projection: DCAProjection generated by :func:`simulate_dca`.
        ax: Optional axes to draw onto. A new figure/axes pair is created when ``None``.
        show: When ``True`` call ``plt.show()`` before returning.
        title: Optional plot title override.

    Returns:
        Matplotlib axes containing the plot.

    Example:
        >>> from pysharpe.visualization.dca import plot_dca_projection, simulate_dca
        >>> proj = simulate_dca(months=3, initial_investment=100.0, monthly_contribution=10.0, annual_return_rate=0.12)
        >>> plot_dca_projection(proj)  # doctest: +SKIP
        <AxesSubplot: ...>
    """

    if ax is None:
        plt = viz_utils.require_matplotlib()
        _, ax = plt.subplots()
    else:
        plt = viz_utils.require_matplotlib()

    ax.plot(
        projection.months,
        projection.balances,
        label="Total Balance",
        linewidth=2,
    )
    ax.plot(
        projection.months,
        projection.contributions,
        label="Total Contributions",
        linewidth=2,
        linestyle="--",
    )

    ax.set_xlabel("Months", fontweight="bold")
    ax.set_ylabel("Amount ($)", fontweight="bold")

    if title is None:
        title = "Dollar-Cost Averaging Projection"
    ax.set_title(title, fontweight="bold")

    ax.legend()
    ax.grid(True)

    if show:
        plt.show()

    return ax
